spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "greeting dev"
  default-value: "Sim"
